export const AppColors = {
  white: 'white',
  red: 'red',
  black: 'black',
  gray: 'gray',
  blue: 'blue',
  mirage: '#1c1c1c',
  darkGray: '#333333',
  vistaWhite: '#f8f8f8',
  lightRed: '#ff6b81',
  shadowColor: '#000',
  lightGrey: '#999',
  lightBackgroundColor: '#ff6b81',
  backgroundColor: 'rgba(255,255,255,0.7)',
  borderColor: '#ccc',
};
