export const AppStrings = {
SEARCH_TXT:"Search Countries...",
REMOVE:"Remove from favorites",
ADD_TO_FAVORITES:"Add to favorites",
GLOBEVIEW:"GlobeView",
VERSION:"Version 1.0.0",
DESCRIPTION:"GlobeView is a demo app created for Optum. It allows you to explore countries around the globe, see weather information, and save your favorite countries.",
DEVELOPER:"Developer",
DEVELOPMENT_TEAM:"Optum Development Team",
CONTACT:"Contact",
SUPPORT_MAIL:"support@optum.com",
PRIVACY_POLICY:"Privacy Policy",
TERMS_SERVICE:"Terms of Service",
CAPITAL:"Capital:",
REGION:"Region:",
SUB_REGION:"Subregion:",
POPULATION:"Population:",
AREA:"Area:",
LANGUAGES:"Languages:",
NA:"N/A",
NO_FAVORITES:"No favorites added yet.",
TERMS_PRIVACY:"Terms & Privacy",
NO_ITEM_FOUND:"No items found",
DETAILS_TXT:"View Details",
};
